[relaychain]
default_command = "../polkadot/target/release/polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

  [[relaychain.nodes]]
  name = "charlie"
  validator = true

  [[relaychain.nodes]]
  name = "dave"
  validator = true

[[parachains]]
id = 1000
cumulus_based = true

  [parachains.collator]
  name = "parachain-1000-collator"
  command = "../sequester-parachain-template/target/release/parachain-template-node"

[[parachains]]
id = 1001
cumulus_based = true

  [parachains.collator]
  name = "parachain-1001-collator"
  command = "../sequester-rococo/target/release/parachain-template-node"
  args = ["--log xcm=trace"]

[[hrmp_channels]]
sender = 1000
recipient = 1001
max_capacity = 8
max_message_size = 512

